export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CASE_STUDIES = "GET_CASE_STUDIES";
export const UPDATE_SELECTED_FILTER = "UPDATE_SELECTED_FILTER";
export const FILTER_CASE_STUDIES = "FILTER_CASE_STUDIES";